#!/usr/bin/python
'''Script to translate lines of laTeX from stdin to nemeth braille in stdout.'''


import sys
import latex_access
import nemeth

while True:
    input = sys.stdin.readline()
    output=latex_access.translate(input,nemeth.table)
    print output

    
