#!/usr/bin/python
'''Script to translate lines of laTeX from stdin to nemeth braille and speech in stdout.'''


import sys

import nemeth
import speech
n=nemeth.nemeth()
s=speech.speech()
while True:
    input = sys.stdin.readline()
    output=n.translate(input)
    print output

    output=s.translate(input)
    print output
    
