#!/usr/bin/python
'''Script to translate lines of laTeX from stdin to  in stdout.'''


import sys
import latex_access.settings


s = latex_access.settings.get_speech_translator("ssml", experimental=True)()


while True:
    input = sys.stdin.readline()
    output=s.translate(input)
    print (output)
    sys.stdout.flush()
