name: CI pipeline

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: set up python ${{ matrix.python-version }}
        uses: action/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run tests
        run: pytest latex_access/tests/test*